{% set name = "jupyter-scatter" %}
{% set version = "0.17.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jupyter_scatter-{{ version }}.tar.gz
  sha256: 86e29d1cc13399401dd602229246632613d5a5952313241a073fbadf89b780b4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host: 
    - python >=3.8
    - hatchling
    - pip
    - hatch-jupyter-builder >=0.5.0
    - nodejs
  run:
    - python >=3.8
    - anywidget >=0.9.0
    - ipywidgets >=7.6,<9
    - ipython
    - matplotlib-base
    - numpy
    - pandas
    - traittypes >=0.2.1
    - typing-extensions

test:
  imports:
    - jscatter
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://jupyter-scatter.dev/
  dev_url: https://github.com/flekschas/jupyter-scatter
  doc_url: https://jupyter-scatter.dev/api
  summary: An interactive scatter plot widget for Jupyter Notebook, Lab, and Google Colab that can handle millions of points and supports view linking
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
