{% set name = "jupyter-scatter" %}
{% set version = "0.21.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jupyter_scatter-{{ version }}.tar.gz
  sha256: 7d6a267043e40d34f0636d7296a51c58a8ae99a8b555edb169e95b1215fbedfa

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
    - hatch-jupyter-builder >=0.5.0
    - nodejs
  run:
    - python >={{ python_min }}
    - anywidget >=0.9.0
    - ipywidgets >=7.6,<9
    - ipython
    - matplotlib-base
    - numpy
    - pandas
    - pooch >=1.3.0
    - pyarrow
    - scipy
    - seaborn
    - traittypes >=0.2.1
    - typing-extensions

test:
  imports:
    - jscatter
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://jupyter-scatter.dev/
  dev_url: https://github.com/flekschas/jupyter-scatter
  doc_url: https://jupyter-scatter.dev/api
  summary: An interactive scatter plot widget for Jupyter Notebook, Lab, and Google Colab that can handle millions of points and supports view linking
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
