schema_version: 1

context:
  name: jupyter-scatter
  version: 0.21.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/jupyter_scatter-${{ version }}.tar.gz
  sha256: 7d6a267043e40d34f0636d7296a51c58a8ae99a8b555edb169e95b1215fbedfa

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
    - hatch-jupyter-builder >=0.5.0
    - nodejs
  run:
    - python >=${{ python_min }}
    - anywidget >=0.9.0
    - ipywidgets >=7.6,<9
    - ipython
    - matplotlib-base
    - numpy
    - pandas
    - pooch >=1.3.0
    - pyarrow
    - scipy
    - seaborn
    - traittypes >=0.2.1
    - typing-extensions

tests:
  - python:
      imports:
        - jscatter
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  summary: An interactive scatter plot widget for Jupyter Notebook, Lab, and Google Colab that can handle millions of points and supports view linking
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://jupyter-scatter.dev/
  repository: https://github.com/flekschas/jupyter-scatter
  documentation: https://jupyter-scatter.dev/api

extra:
  recipe-maintainers:
    - thewchan
